site_name: exbip-python
theme:
  name: material
  palette:
  - scheme: slate
    primary: black
    accent: blue
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
